package iss;

import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

import sensors.HumiditySensor;
import sensors.RainSensor;
import sensors.SensorInterface;
import sensors.TemperatureSensor;
import sensors.WindSensor;

/**
 * This is the ISS application, which will capture
 * data generated by from sensors.
 * @author Phong Hoang Le
 * @version 1.0
 */
public class ISS {

	public ISS() {
	}
	public void run() {
		//TODO: implement this
	}
	
}