package iss;

import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

import sensors.HumiditySensor;
import sensors.RainSensor;
import sensors.SensorInterface;
import sensors.TemperatureSensor;
import sensors.WindSensor;

/**
 * This is the ISS application, which will capture
 * data generated by from sensors.
 * @author Phong Hoang Le
 * @author Benjamin Munoz
 * @version 1.0
 */
public class ISS {

    /** Timer for all sensors. */
    private Timer myTimer;
    
    /** All sensors. */
    private SensorInterface humid, rain, temp, wind;
    
    /**
     * Constructor method.
     */
    public ISS() {
        humid = new HumiditySensor();
        rain = new RainSensor();
        temp = new TemperatureSensor();
        wind = new WindSensor();
    }
    
    /**
     * This method will initialize very timer for all sensors.
     */
    public void run() {
        TimerTask task = new TimerTask() {
            private String output;
            
            public void run() {
                output = (new Date()).toString() + "\n";
                output += humid.getData() + "\n";
                output += rain.getData() + "\n";
                output += temp.getData() + "\n";
                output += wind.getData() + "\n";
                System.out.println(output);
                System.out.println();
            }
        };
        
        myTimer = new Timer();
        
        myTimer.schedule(task, 0, 3000);
    }
    
}